Quiz Management/Controllers/QuestionController.cs
using System.Data;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using QuizApplication.Models;
using CrudOperationEntityFrameWork.Constants;

namespace QuizApplication.Controllers
{
    public class QuestionController : Controller
    {
        private IConfiguration configuration;
        public QuestionController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult QuestionList()
        {
            FillQuestionLevelDropDown();
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Question_SelectAll";
            command.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }

        public IActionResult QuestionDelete(int QuestionID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_MST_Question_DeleteByPk";
                sqlCommand.Parameters.Add("@QuestionID", SqlDbType.Int).Value = QuestionID;
                sqlCommand.ExecuteNonQuery();

                TempData["SuccessMessage"] = "Deleted Succesfully";
                return RedirectToAction("QuestionList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Can't be deleted";
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("QuestionList");
        }

        public IActionResult QuestionForm(int QuestionID)
        {
            if (QuestionID == 0)
            {
                TempData["PageTitle"] = "Add Question";
            }
            else
            {
                TempData["PageTitle"] = "Edit Question";
            }

            //------------Question Level Drop Down Model
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");

            FillQuestionLevelDropDown();

            //------------User Drop Down Model

            string userConnectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection userSqlConnection = new SqlConnection(userConnectionString);
            userSqlConnection.Open();
            SqlCommand userSqlCommand = userSqlConnection.CreateCommand();
            userSqlCommand.CommandType = CommandType.StoredProcedure;
            userSqlCommand.CommandText = "PR_MST_User_SelectAll";
            SqlDataReader userReader = userSqlCommand.ExecuteReader();
            DataTable userDataTable = new DataTable();
            userDataTable.Load(userReader);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in userDataTable.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }
            ViewBag.UserList = userList;

            //---------------------------Question Backend Code 

            ViewBag.QuestionID = QuestionID;
            SqlConnection QuestionSqlConnection = new SqlConnection(questionLevelConnectionString);
            QuestionSqlConnection.Open();
            SqlCommand questionSqlCommand = QuestionSqlConnection.CreateCommand();
            questionSqlCommand.CommandType = CommandType.StoredProcedure;
            questionSqlCommand.CommandText = "PR_MST_Question_SelectByPK";
            questionSqlCommand.Parameters.AddWithValue("@QuestionID", QuestionID);
            SqlDataReader questionReader = questionSqlCommand.ExecuteReader();
            DataTable questionTable = new DataTable();
            questionTable.Load(questionReader);
            QuestionModel questionModel = new QuestionModel();

            foreach (DataRow dataRow in questionTable.Rows)
            {
                questionModel.QuestionID = Convert.ToInt32(@dataRow["QuestionID"]);
                questionModel.QuestionText = @dataRow["QuestionText"].ToString();
                questionModel.QuestionLevelID = Convert.ToInt32(@dataRow["QuestionLevelID"]);
                questionModel.OptionA = @dataRow["OptionA"].ToString();
                questionModel.OptionB = @dataRow["OptionB"].ToString();
                questionModel.OptionC = @dataRow["OptionC"].ToString();
                questionModel.OptionD = @dataRow["OptionD"].ToString();
                questionModel.CorrectOption = @dataRow["CorrectOption"].ToString();
                questionModel.QuestionMarks = Convert.ToInt32(@dataRow["QuestionMarks"]);
                questionModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }
            Console.WriteLine(questionModel);
            return View("QuestionForm", questionModel);
        }

        private void FillQuestionLevelDropDown()
        {
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection questionLevelSqlConnection = new SqlConnection(questionLevelConnectionString);
            questionLevelSqlConnection.Open();
            SqlCommand questionLevelSqlCommand = questionLevelSqlConnection.CreateCommand();
            questionLevelSqlCommand.CommandType = CommandType.StoredProcedure;
            questionLevelSqlCommand.CommandText = "PR_MST_QuestionLevel_SelectAll";
            questionLevelSqlCommand.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));

            SqlDataReader questionLevelReader = questionLevelSqlCommand.ExecuteReader();
            DataTable questionLevelDataTable = new DataTable();
            questionLevelDataTable.Load(questionLevelReader);
            List<QuestionLevelDropDown> questionLevelList = new List<QuestionLevelDropDown>();
            foreach (DataRow data in questionLevelDataTable.Rows)
            {
                QuestionLevelDropDown questionLevelDropDownModel = new QuestionLevelDropDown();
                questionLevelDropDownModel.QuestionLevelID = Convert.ToInt32(data["QuestionLevelID"]);
                questionLevelDropDownModel.QuestionLevel = data["QuestionLevel"].ToString();
                questionLevelList.Add(questionLevelDropDownModel);
            }
            ViewBag.QuestionLevelList = questionLevelList;
        }

        public IActionResult QuestionSave(QuestionModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.QuestionID == 0)
                {
                    command.CommandText = "PR_MST_Question_Insert";
                    command.Parameters.Add("@Created", SqlDbType.DateTime).Value = DateTime.Now;
                }
                else
                {
                    command.CommandText = "PR_MST_Question_UpdateByPk";
                    command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionID;
                }
                command.Parameters.Add("@QuestionText", SqlDbType.VarChar).Value = model.QuestionText;
                command.Parameters.Add("@QuestionLevelID", SqlDbType.Int).Value = model.QuestionLevelID;
                command.Parameters.Add("@OptionA", SqlDbType.VarChar).Value = model.OptionA;
                command.Parameters.Add("@OptionB", SqlDbType.VarChar).Value = model.OptionB;
                command.Parameters.Add("@OptionC", SqlDbType.VarChar).Value = model.OptionC;
                command.Parameters.Add("@OptionD", SqlDbType.VarChar).Value = model.OptionD;
                command.Parameters.Add("@CorrectOption", SqlDbType.VarChar).Value = model.CorrectOption;
                command.Parameters.Add("@QuestionMarks",SqlDbType.Int).Value = model.QuestionMarks;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = HttpContext.Session.GetString(Constants.USERID_SESSION_KEY);
                command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = DateTime.Now;
                command.ExecuteNonQuery();
                return RedirectToAction("QuestionList");
            }
            return View("QuestionForm", model);
        }

        //[HttpPost]
        //public IActionResult QuestionSearch(int? questionLevel, string questionText, int? questionMarks)
        //{
        //    string connectionString = configuration.GetConnectionString("ConnectionString");
        //    using (SqlConnection connection = new SqlConnection(connectionString))
        //    {
        //        connection.Open();

Quiz Management/Controllers/QuizController.cs
using System.Data;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using QuizApplication.Models;
using CrudOperationEntityFrameWork.Constants;


namespace QuizApplication.Controllers
{
    public class QuizController : Controller
    {
        private IConfiguration configuration;
        public QuizController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult QuizList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Quiz_SelectAll";
            command.Parameters.AddWithValue("@UserID",HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }

        public IActionResult QuizDelete(int QuizID) 
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_MST_Quiz_DeleteByPk";
                sqlCommand.Parameters.Add("@QuizID", SqlDbType.Int).Value = QuizID;
                sqlCommand.ExecuteNonQuery();
                TempData["SuccessMessage"] = "Deleted Succesfully";
                return RedirectToAction("QuizList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Can't be deleted";
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("QuizList");
        }
        [HttpGet]

        public IActionResult QuizForm(int QuizID)
        {
            if (QuizID == 0)
            {
                TempData["PageTitle"] = "Add Quiz";
            }
            else
            {
                TempData["PageTitle"] = "Edit Quiz";
            }

            //------------User Drop Down Model

            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection sqlConnection1 = new SqlConnection(connectionString);
            sqlConnection1.Open();
            SqlCommand sqlCommand1 = sqlConnection1.CreateCommand();
            sqlCommand1.CommandType = CommandType.StoredProcedure;
            sqlCommand1.CommandText = "PR_MST_User_SelectAll";
            SqlDataReader reader1 = sqlCommand1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }
            ViewBag.UserList = userList;

            //---------------------------Quiz Backend Code 
            ViewBag.QuizID = QuizID;
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            sqlConnection.Open();
            SqlCommand sqlCommand = sqlConnection.CreateCommand();
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_MST_Quiz_SelectByID";
            sqlCommand.Parameters.AddWithValue("@QuizID", QuizID);
            SqlDataReader reader = sqlCommand.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            QuizModel quizModel = new QuizModel();

            foreach (DataRow dataRow in table.Rows)
            {
                quizModel.QuizID = Convert.ToInt32(@dataRow["QuizID"]);
                quizModel.QuizName = @dataRow["QuizName"].ToString();
                quizModel.TotalQuestions = Convert.ToInt32(@dataRow["TotalQuestions"]);
                quizModel.QuizDate = Convert.ToDateTime(@dataRow["QuizDate"]);

            }

            return View("QuizForm", quizModel);
        }

        public IActionResult QuizSave(QuizModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.QuizID == 0)
                {
                    command.CommandText = "PR_MST_Quiz_Insert";
                    command.Parameters.Add("@Created", SqlDbType.DateTime).Value = DateTime.Now;
                }
                else
                {
                    command.CommandText = "PR_MST_Quiz_UpdateByPK";
                    command.Parameters.Add("@QuizID", SqlDbType.Int).Value = model.QuizID;
                }
                command.Parameters.Add("@QuizName", SqlDbType.VarChar).Value = model.QuizName;
                command.Parameters.Add("@TotalQuestions", SqlDbType.Int).Value = model.TotalQuestions;
                command.Parameters.Add("@QuizDate", SqlDbType.DateTime).Value = model.QuizDate;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = HttpContext.Session.GetString(Constants.USERID_SESSION_KEY);
                command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = DateTime.Now;
                command.ExecuteNonQuery();
                return RedirectToAction("QuizList");
            }
            return View("QuizForm", model);
        }
    }
}

Quiz Management/Views/Home/Index.cshtml
@using System.Data
@model UserHomePageDisplayModel

<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Admin</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section dashboard">
    <div class="row">
        <!-- Left side columns -->
        <div class="col-lg-12">
            <div class="row">
                <!-- Quiz Card -->
                    <div class="col-xxl-4 col-md-6">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Total Quiz</h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                   <a asp-action="QuizList" asp-controller="Quiz"><i class="bi bi-book"></i></a>
                                </div>
                                <div class="ps-3">
                                    <a asp-action="QuizList" asp-controller="Quiz"><h5>@TempData.Peek("QuizCount")</h5></a>
                                </div>
                            </div>
                        </div>
               
                    </div>
                </div> 
                <!-- End Quiz Card -->
                <!-- Question Card -->
                <div class="col-xxl-4 col-md-6">
                    <div class="card info-card revenue-card">
                        <div class="card-body">
                            <h5 class="card-title">Total Question</h5>

                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                     <a asp-action="QuestionList" asp-controller="Question"><i class="bi bi-question-circle"></i></a>
                                </div>
                                <div class="ps-3">
                                    <a asp-action="QuestionList" asp-controller="Question"><h5>@TempData.Peek("QuestionCount")</h5></a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div><!-- End Question Card -->
                <!-- Question Levels Card -->
                <div class="col-xxl-4 col-md-6">
                    <div class="card info-card revenue-card">
                        <div class="card-body">
                            <h5 class="card-title">Total Question Levels</h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                     <a asp-action="QuestionLevelList" asp-controller="QuestionLevel"><i class="bi bi-question-circle"></i></a>
                                </div>
                                <div class="ps-3">
                                    <a asp-action="QuestionLevelList" asp-controller="QuestionLevel"><h5>@TempData.Peek("QuestionLevelCount")</h5></a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div><!-- End Question Levels Card -->
            </div>
        </div><!-- End Left side columns -->

        <!-------------------------------------------------------------------------------------------------------->
        <!-- Table Start With Recent Quiz -->
        <div class="col-lg-6 ">
            <div class="card">
                <div class="card-body ">
                    <h5 class="card-title">Recent 10 Quiz</h5>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Quiz ID</th>
                                <th scope="col">Quiz Name</th>
                                <th scope="col">Total Question</th>
                                <th scope="col">Quiz Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var quiz in Model.quizData)
                            {
                                <tr>
                                    <td>@quiz.QuizID</td>
                                    <td>@quiz.QuizName</td>
                                    <td>@quiz.TotalQuestions</td>
                                    <td>@quiz.QuizDate</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <!-- End Recent 10 Quiz rows -->
                </div>
            </div>
        </div>

        <!-------------------------------------------------------------------------------------------------------->
        <!-- Table Start with Recent Question -->
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Recent 10 Questions</h5>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Question ID</th>
                                <th scope="col">Question</th>
                                <th scope="col">Question Marks</th>
                                <th scope="col">Correct Option</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var question in Model.questionData){
                            <tr>
                                <td>@question.QuestionID</td>
                                <td>@question.QuestionText</td>
                                <td>@question.QuestionMarks</td>
                                <td>@question.CorrectOption</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                    <!-- End Recent 10 Question rows -->

                </div>
          </div>
      </div>    
      </div>
</section>