Quiz Management/Controllers/QuestionController.cs
using System.Data;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using QuizApplication.Models;
using CrudOperationEntityFrameWork.Constants;

namespace QuizApplication.Controllers
{
    public class QuestionController : Controller
    {
        private IConfiguration configuration;
        public QuestionController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        public IActionResult QuestionList()
        {
            FillQuestionLevelDropDown();
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Question_SelectAll";
            command.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }

        public IActionResult QuestionDelete(int QuestionID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_MST_Question_DeleteByPk";
                sqlCommand.Parameters.Add("@QuestionID", SqlDbType.Int).Value = QuestionID;
                sqlCommand.ExecuteNonQuery();

                TempData["SuccessMessage"] = "Deleted Succesfully";
                return RedirectToAction("QuestionList");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Can't be deleted";
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("QuestionList");
        }

        public IActionResult QuestionForm(int QuestionID)
        {
            if (QuestionID == 0)
            {
                TempData["PageTitle"] = "Add Question";
            }
            else
            {
                TempData["PageTitle"] = "Edit Question";
            }

            //------------Question Level Drop Down Model
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");

            FillQuestionLevelDropDown();

            //------------User Drop Down Model

            string userConnectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection userSqlConnection = new SqlConnection(userConnectionString);
            userSqlConnection.Open();
            SqlCommand userSqlCommand = userSqlConnection.CreateCommand();
            userSqlCommand.CommandType = CommandType.StoredProcedure;
            userSqlCommand.CommandText = "PR_MST_User_SelectAll";
            SqlDataReader userReader = userSqlCommand.ExecuteReader();
            DataTable userDataTable = new DataTable();
            userDataTable.Load(userReader);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in userDataTable.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }
            ViewBag.UserList = userList;

            //---------------------------Question Backend Code 

            ViewBag.QuestionID = QuestionID;
            SqlConnection QuestionSqlConnection = new SqlConnection(questionLevelConnectionString);
            QuestionSqlConnection.Open();
            SqlCommand questionSqlCommand = QuestionSqlConnection.CreateCommand();
            questionSqlCommand.CommandType = CommandType.StoredProcedure;
            questionSqlCommand.CommandText = "PR_MST_Question_SelectByPK";
            questionSqlCommand.Parameters.AddWithValue("@QuestionID", QuestionID);
            SqlDataReader questionReader = questionSqlCommand.ExecuteReader();
            DataTable questionTable = new DataTable();
            questionTable.Load(questionReader);
            QuestionModel questionModel = new QuestionModel();

            foreach (DataRow dataRow in questionTable.Rows)
            {
                questionModel.QuestionID = Convert.ToInt32(@dataRow["QuestionID"]);
                questionModel.QuestionText = @dataRow["QuestionText"].ToString();
                questionModel.QuestionLevelID = Convert.ToInt32(@dataRow["QuestionLevelID"]);
                questionModel.OptionA = @dataRow["OptionA"].ToString();
                questionModel.OptionB = @dataRow["OptionB"].ToString();
                questionModel.OptionC = @dataRow["OptionC"].ToString();
                questionModel.OptionD = @dataRow["OptionD"].ToString();
                questionModel.CorrectOption = @dataRow["CorrectOption"].ToString();
                questionModel.QuestionMarks = Convert.ToInt32(@dataRow["QuestionMarks"]);
                questionModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
            }
            Console.WriteLine(questionModel);
            return View("QuestionForm", questionModel);
        }

        private void FillQuestionLevelDropDown()
        {
            string questionLevelConnectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection questionLevelSqlConnection = new SqlConnection(questionLevelConnectionString);
            questionLevelSqlConnection.Open();
            SqlCommand questionLevelSqlCommand = questionLevelSqlConnection.CreateCommand();
            questionLevelSqlCommand.CommandType = CommandType.StoredProcedure;
            questionLevelSqlCommand.CommandText = "PR_MST_QuestionLevel_SelectAll";
            questionLevelSqlCommand.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));

            SqlDataReader questionLevelReader = questionLevelSqlCommand.ExecuteReader();
            DataTable questionLevelDataTable = new DataTable();
            questionLevelDataTable.Load(questionLevelReader);
            List<QuestionLevelDropDown> questionLevelList = new List<QuestionLevelDropDown>();
            foreach (DataRow data in questionLevelDataTable.Rows)
            {
                QuestionLevelDropDown questionLevelDropDownModel = new QuestionLevelDropDown();
                questionLevelDropDownModel.QuestionLevelID = Convert.ToInt32(data["QuestionLevelID"]);
                questionLevelDropDownModel.QuestionLevel = data["QuestionLevel"].ToString();
                questionLevelList.Add(questionLevelDropDownModel);
            }
            ViewBag.QuestionLevelList = questionLevelList;
        }

        public IActionResult QuestionSave(QuestionModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.QuestionID == 0)
                {
                    command.CommandText = "PR_MST_Question_Insert";
                    command.Parameters.Add("@Created", SqlDbType.DateTime).Value = DateTime.Now;
                }
                else
                {
                    command.CommandText = "PR_MST_Question_UpdateByPk";
                    command.Parameters.Add("@QuestionID", SqlDbType.Int).Value = model.QuestionID;
                }
                command.Parameters.Add("@QuestionText", SqlDbType.VarChar).Value = model.QuestionText;
                command.Parameters.Add("@QuestionLevelID", SqlDbType.Int).Value = model.QuestionLevelID;
                command.Parameters.Add("@OptionA", SqlDbType.VarChar).Value = model.OptionA;
                command.Parameters.Add("@OptionB", SqlDbType.VarChar).Value = model.OptionB;
                command.Parameters.Add("@OptionC", SqlDbType.VarChar).Value = model.OptionC;
                command.Parameters.Add("@OptionD", SqlDbType.VarChar).Value = model.OptionD;
                command.Parameters.Add("@CorrectOption", SqlDbType.VarChar).Value = model.CorrectOption;
                command.Parameters.Add("@QuestionMarks",SqlDbType.Int).Value = model.QuestionMarks;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = HttpContext.Session.GetString(Constants.USERID_SESSION_KEY);
                command.Parameters.Add("@Modified", SqlDbType.DateTime).Value = DateTime.Now;
                command.ExecuteNonQuery();
                return RedirectToAction("QuestionList");
            }
            return View("QuestionForm", model);
        }

        //[HttpPost]
        //public IActionResult QuestionSearch(int? questionLevel, string questionText, int? questionMarks)
        //{
        //    string connectionString = configuration.GetConnectionString("ConnectionString");
        //    using (SqlConnection connection = new SqlConnection(connectionString))
        //    {
        //        connection.Open();

Quiz Management/Controllers/QuizWiseQuestionController.cs
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using CrudOperationEntityFrameWork.Constants;


namespace QuizApplication.Controllers
{
    public class QuizWiseQuestionController : Controller
    {
        private IConfiguration configuration;
        public QuizWiseQuestionController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }
        public IActionResult QuizWiseQuestionList()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Quiz_SelectAll";
            command.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }

        public IActionResult QuizWiseQuestionForm()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Question_SelectAll";
            command.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));

            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }
       
        public IActionResult QuizWiseQuestionDetails()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "PR_MST_Question_SelectAll";
            command.Parameters.AddWithValue("@UserID", HttpContext.Session.GetString(Constants.USERID_SESSION_KEY));

            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new();
            table.Load(reader);
            return View(table);
        }

        public IActionResult QuizWiseQuestionQuizDelete(int QuizID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_MST_Quiz_DeleteByPk";
                sqlCommand.Parameters.Add("@QuizID", SqlDbType.Int).Value = QuizID;
                sqlCommand.ExecuteNonQuery();

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Can't be deleted";
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("QuizWiseQuestionList");
        }

        public IActionResult QuizWiseQuestionDelete(int QuestionID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_MST_Question_DeleteByPk";
                sqlCommand.Parameters.Add("@QuestionID", SqlDbType.Int).Value = QuestionID;
                sqlCommand.ExecuteNonQuery();

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Can't be deleted";
                Console.WriteLine(ex.ToString());
            }
            return RedirectToAction("QuizWiseQuestionList");
        }
    }
}

Quiz Management/Views/QuizWiseQuestion/QuizWiseQuestionDetails.cshtml
@model DataTable
@using System.Data


<div class="pagetitle">
    <h1>Quiz Wise Question Details</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="QuizWiseQuestionList" asp-controller="QuizWiseQuestion">Quiz Wise Question List</a></li>
            <li class="breadcrumb-item active">Quiz Wise Question Details</li>
        </ol>
    </nav>
</div><!-- End Page Title -->


<div class="card">
    <div class="card-body">
        <h5 class="card-title">Quiz Wise Question Details</h5>
        <div class="d-flex p-3 justify-content-end">
            <a asp-action="QuestionLevelForm" asp-controller="QuestionLevel" class="btn btn-danger w-20">
                Deleted Selected
            </a> &nbsp;&nbsp;&nbsp;
            <a asp-action="QuestionForm" asp-controller="Question" class="btn btn-primary w-20">
                Add Question 
            </a>
        </div>
            <p>Quiz Name : English Grammer Test</p>  
            <p>Total Question in Quiz : 10</p>       
        <!-- Table with stripped rows -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">
                        <input class="form-check-input border border-dark" type="checkbox" value="" onclick="checkUncheck(this)" id="">
                    </th>
                    <th scope="col">Question Text</th>
                    <th scope="col">Option A</th>
                    <th scope="col">Option B</th>
                    <th scope="col">Option C</th>
                    <th scope="col">Option D</th>
                    <th scope="col">Correct Option</th>
                    <th scope="col">Marks</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.Rows)
                {
                    <tr>
                        <th scope="row"> <input class="form-check-input border border-dark" name="ch" type="checkbox" value="" id=""></th>
                        <td>@row["QuestionText"]</td>
                        <td>@row["OptionA"]</td>
                        <td>@row["OptionB"]</td>
                        <td>@row["OptionC"]</td>
                        <td>@row["OptionD"]</td>
                        <td>@row["CorrectOption"]</td>
                        <td>@row["QuestionMarks"]</td>
                        <td>
                            <a asp-action="QuizWiseQuestionDelete" asp-route-QuestionID="@row["QuestionID"]" onclick="confirmDelete()" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
     <!-- End Table with stripped rows -->
    </div>
</div>


<script type="text/javascript">
    function checkUncheck(main){
         let all = document.getElementsByName('ch');
         for(var i=0;i<all.length;i++)
         {
            all[i].checked = main.checked
         }
    }
</script>

<script>
    function confirmDelete() {
        return confirm("Are you Sure! You want to Delete this record from Quiz?")
    }
</script>

Quiz Management/Views/QuizWiseQuestion/QuizWiseQuestionForm.cshtml
@model DataTable
@using System.Data


<div class="pagetitle">
    <h1>Add Quiz Wise Question</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">Quiz Wise Questions</li>
            <li class="breadcrumb-item active">Quiz Wise Questions AddEdit</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<section class="section">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Quiz Wise Questions Add/Edit</h5>
                <!-- No Labels Form -->
                <form class="row g-3">
                    <div class="col-md-4">
                        <label for="exampleFormControlInput1" class="form-label">Total Question Allowed</label>
                        <input type="text" class="form-control border border-dark" placeholder="Total Question Allowed">
                    </div>
                    <div class="col-md-4">
                        <label for="exampleFormControlInput1" class="form-label">Selected Question Count</label>
                        <input type="text" class="form-control border border-dark" placeholder="Selected Question Count">
                    </div>
                    <div class="col-md-4">
                        <label for="exampleFormControlInput1" class="form-label">Select Quiz</label>
                        <select class="form-select border border-black" aria-label="Default select example">
                            <option selected>Open this select Quiz</option>
                            <option value="1">XYZ</option>
                            <option value="2">ABC</option>
                            <option value="3">DEF</option>
                        </select>
                    </div>
                </form>
            </div>

            <div class="card">
                <div class="card-body">
                    <!-- Default Table -->
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">
                                    <input class="form-check-input border border-dark" type="checkbox" value="" onclick="checkUncheck(this)" id="">
                                </th>
                                <th scope="col">Question</th>
                                <th scope="col">Option A</th>
                                <th scope="col">Option B</th>
                                <th scope="col">Option C</th>
                                <th scope="col">Option D</th>
                                <th scope="col">Answer</th>
                                <th scope="col">Marks</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (DataRow row in Model.Rows)
                        {
                            <tr>
                                <th scope="row">
                                    <input class="form-check-input border border-black" name="ch" type="checkbox" value="" id="">
                                </th>
                                <td>@row["QuestionText"]</td>
                                <td>@row["OptionA"]</td>
                                <td>@row["OptionB"]</td>
                                <td>@row["OptionC"]</td>
                                <td>@row["OptionD"]</td>
                                <td>@row["CorrectOption"]</td>
                                <td>@row["QuestionMarks"]</td>
                            </tr>
                            }
                           
                        </tbody>
                    </table>

                    <div class="text-start">
                        <button type="submit" class="btn btn-success">Save</button>
                        <a asp-action="QuizWiseQuestionList" asp-controller="QuizWiseQuestion" class="btn btn-danger">Cancel</a>
                    </div>
                    <!-- End Default Table Example -->
                </div>
            </div>
        </div>
    </div>
</section>


<script type="text/javascript">
    function checkUncheck(main){
         let all = document.getElementsByName('ch');
         for(var i=0;i<all.length;i++)
         {
            all[i].checked = main.checked
         }
    }
</script>


Quiz Management/Views/QuizWiseQuestion/QuizWiseQuestionList.cshtml
@model DataTable
@using System.Data

<div class="pagetitle">
    <h1>Quiz Wise Question List</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item">Quiz Wise Question</li>
            <li class="breadcrumb-item active">Quiz Wise Question List</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<section class="section">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Search Quiz Wise Question</h5>
                <!-- No Labels Form -->
                <form class="row g-3">
                    <div class="col-md-4">
                        <label for="exampleFormControlInput1" class="form-label">Select Quiz</label>
                        <select class="form-select border border-black" aria-label="Default select example">
                            <option selected>Open this select Quiz</option>
                            <option value="1">Karan</option>
                            <option value="2">Yash</option>
                            <option value="3">Nikhil</option>
                        </select>
                    </div>
                    
                    <div class="text-start">
                        <button type="submit" class="btn btn-success">Search</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </form><!-- End No Labels Form -->
                <br>
                <h2 class="card-title">Quiz Wise Question List</h2>
                <div class="d-flex p-3 justify-content-end">
                    <a asp-action="QuizWiseQuestionForm" asp-controller="QuizWiseQuestion" class="btn btn-primary w-20">
                        <i class="bi bi-plus"></i> Add Quiz Wise Question
                    </a>
                </div>
                <table class="table datatable">

                    <thead>
                        <tr>
                            <th>Quiz Name</th>
                            <th>Entered Questions</th>
                            <th>User Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow row in Model.Rows)
                        {
                            <tr>
                                <td>@row["QuizName"]</td>
                                <td>@row["TotalQuestions"]</td>
                                <td>@row["UserName"]</td>
                                <td>
                                    <a asp-controller="QuizWiseQuestion" asp-action="QuizWiseQuestionDetails" class="btn btn-success btn-sm"><i class="bi bi-eye"></i></a>
                                    <a asp-controller="QuizWiseQuestion" asp-action="QuizWiseQuestionForm" asp-route-QuizID="@row["QuizID"]" class="btn btn-primary btn-sm"><i class="bi bi-pencil"></i></a>
                                    <a asp-action="QuizWiseQuestionQuizDelete" asp-route-QuizID="@row["QuizID"]" onclick="confirmDelete()" class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<script>
    function confirmDelete() {
        return confirm("Are you Sure! You want to Delete this record from Question?")
    }
</script>